# Generated by Django 5.1.3 on 2024-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockInterviews', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='body_language_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='clarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
