# Generated by Django 5.1.3 on 2024-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockInterviews', '0003_feedback_body_language_score_feedback_clarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='avd_sentence_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='eye_contact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='filler_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='grammar_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
